export const dummyStats = [
  {
    id: 1,
    heading: "Total reservations today",
    stat: 123,
    isIncreased: true,
    percentage: 0.0856,
  },
  {
    id: 2,
    heading: "Seat Occupancy rate",
    stat: "20 / 29", // Fixed the calculation format
  },
  {
    id: 3,
    heading: "No show rate",
    stat: "8 / 10",
  },
];

export const dummyUpdates = [
  {
    id: 1,
    updateMessage: "New reservation made for Table 7",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
    fallbackName: "JD",
  },
  {
    id: 2,
    updateMessage: "Cancelled reservation for Party of 4",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    fallbackName: "SA",
  },
  {
    id: 3,
    updateMessage: "Modified booking time for Table 12",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    fallbackName: "MK",
  },
  {
    id: 4,
    updateMessage: "Special request added to Reservation #45",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    fallbackName: "EM",
  },
  {
    id: 5,
    updateMessage: "Table 3 marked as occupied",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    fallbackName: "JH",
  },
  {
    id: 6,
    updateMessage: "Guest check-in for Table 9",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    fallbackName: "LS",
  },
  {
    id: 7,
    updateMessage: "Updated party size for Reservation #23",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tom",
    fallbackName: "TM",
  },
  {
    id: 8,
    updateMessage: "No-show recorded for Table 5",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anna",
    fallbackName: "AN",
  },
  {
    id: 9,
    updateMessage: "Table 15 marked as available",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    fallbackName: "DV",
  },
  {
    id: 10,
    updateMessage: "New group reservation for 8 people",
    imageSrc: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kate",
    fallbackName: "KT",
  },
];

export const TableColumns = [
  { key: "customerName", label: "Customer Name" },
  { key: "partySize", label: "Size" },
  { key: "date", label: "Date" },
  { key: "time", label: "Time" },
  { key: "table", label: "Table" },
  { key: "phone", label: "Phone No" },
  { key: "status", label: "Status" },
  { key: "actions", label: "Actions", type: "action", actions: ["edit"] },
];
export const DUMMY_ACTIONS = ["View Details", "Edit", "Delete"];

export const DUMMY_DATA = [
  {
    customerName: "John Doe",
    partySize: 2,
    date: "07/06/25",
    time: "10:30 AM",
    table: 34,
    phone: "0000000000",
    status: "Confirmed",
    specialRequests: "Window seat",
  },
  {
    customerName: "Alice Smith",
    partySize: 3,
    date: "07/06/25",
    time: "10:30 AM",
    table: 34,
    phone: "9999999999",
    status: "Pending",
    specialRequests: "Birthday celebration",
  },
  {
    customerName: "Robert Chang",
    partySize: 4,
    date: "07/06/25",
    time: "10:30 AM",
    table: 39,
    phone: "8888888888",
    status: "Confirmed",
    specialRequests: "Allergic to nuts",
  },
  {
    customerName: "Nora Patel",
    partySize: 5,
    date: "07/06/25",
    time: "11:00 AM",
    table: 31,
    phone: "7777777777",
    status: "Confirmed",
    specialRequests: "High chair needed",
  },
  {
    customerName: "Leo Fernandez",
    partySize: 2,
    date: "07/06/25",
    time: "11:36 AM",
    table: 31,
    phone: "6666666666",
    status: "Cancelled",
    specialRequests: "None",
  },
  {
    customerName: "Zara Khalid",
    partySize: 7,
    date: "07/06/25",
    time: "11:30 AM",
    table: 33,
    phone: "5555555555",
    status: "Confirmed",
    specialRequests: "Halal options",
  },
  {
    customerName: "Bilal Ahmed",
    partySize: 2,
    date: "07/06/25",
    time: "10:00 PM",
    table: 34,
    phone: "3333333333",
    status: "Confirmed",
    specialRequests: "Quiet area",
  },
  {
    customerName: "Fatima Noor",
    partySize: 9,
    date: "07/06/25",
    time: "10:30 PM",
    table: 34,
    phone: "2222222222",
    status: "Confirmed",
    specialRequests: "Private room",
  },
  {
    customerName: "Bilal Ahmed",
    partySize: 2,
    date: "07/06/25",
    time: "10:00 PM",
    table: 34,
    phone: "3333333333",
    status: "Confirmed",
    specialRequests: "Quiet area",
  },
  {
    customerName: "Fatima Noor",
    partySize: 9,
    date: "07/06/25",
    time: "10:30 PM",
    table: 34,
    phone: "2222222222",
    status: "Confirmed",
    specialRequests: "Private room",
  },
  {
    customerName: "Bilal Ahmed",
    partySize: 2,
    date: "07/06/25",
    time: "10:00 PM",
    table: 34,
    phone: "3333333333",
    status: "Confirmed",
    specialRequests: "Quiet area",
  },
  {
    customerName: "Fatima Noor",
    partySize: 9,
    date: "07/06/25",
    time: "10:30 PM",
    table: 34,
    phone: "2222222222",
    status: "Confirmed",
    specialRequests: "Private room",
  },
  {
    customerName: "Bilal Ahmed",
    partySize: 2,
    date: "07/06/25",
    time: "10:00 PM",
    table: 34,
    phone: "3333333333",
    status: "Confirmed",
    specialRequests: "Quiet area",
  },
  {
    customerName: "Fatima Noor",
    partySize: 9,
    date: "07/06/25",
    time: "10:30 PM",
    table: 34,
    phone: "2222222222",
    status: "Confirmed",
    specialRequests: "Private room",
  },
  {
    customerName: "Bilal Ahmed",
    partySize: 2,
    date: "07/06/25",
    time: "10:00 PM",
    table: 34,
    phone: "3333333333",
    status: "Confirmed",
    specialRequests: "Quiet area",
  },
  {
    customerName: "Fatima Noor",
    partySize: 9,
    date: "07/06/25",
    time: "10:30 PM",
    table: 34,
    phone: "2222222222",
    status: "Confirmed",
    specialRequests: "Private room",
  },
];

export const BarsData = [
  { name: "Jan", activity: 100 },
  { name: "Feb", activity: 140 },
  { name: "Mar", activity: 140 },
  { name: "Apr", activity: 230 },
  { name: "May", activity: 270 },
  { name: "Jun", activity: 190 },
  { name: "Jul", activity: 230 },
  { name: "Aug", activity: 100 },
  { name: "Sep", activity: 270 },
  { name: "Oct", activity: 330 },
  { name: "Nov", activity: 370 },
  { name: "Dec", activity: 400 },
  { name: "Jan", activity: 100 },
  { name: "Feb", activity: 270 },
  { name: "Mar", activity: 330 },
  { name: "Apr", activity: 400 },
];
export const supadmincolumns = [
  { 
    key: "imageUrl", 
    label: "Restaurant",
    type: "image" 
  },
  { key: "location", label: "Location" },
  { key: "totalBookings", label: "Total Bookings" },
  { key: "revenue", label: "Revenue" },
  { key: "rating", label: "Rating" },
  { key: "status", label: "Status" },
];

export const supadmin = [
  {
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=40&h=40&fit=crop&crop=center",
    name: "The Golden Spoon",
    location: "New York, NY",
    totalBookings: "1,247",
    revenue: "$45,230",
    rating: "4.8",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=40&h=40&fit=crop&crop=center",
    name: "Bella Vista",
    location: "Los Angeles, CA",
    totalBookings: "987",
    revenue: "$38,450",
    rating: "4.6",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=40&h=40&fit=crop&crop=center",
    name: "Ocean Breeze",
    location: "Miami, FL",
    totalBookings: "1,156",
    revenue: "$52,180",
    rating: "4.9",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=40&h=40&fit=crop&crop=center",
    name: "Mountain View Bistro",
    location: "Denver, CO",
    totalBookings: "743",
    revenue: "$28,920",
    rating: "4.4",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=40&h=40&fit=crop&crop=center",
    name: "Urban Kitchen",
    location: "Chicago, IL",
    totalBookings: "1,389",
    revenue: "$61,750",
    rating: "4.7",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=40&h=40&fit=crop&crop=center",
    name: "Sunset Grill",
    location: "San Francisco, CA",
    totalBookings: "892",
    revenue: "$41,320",
    rating: "4.5",
    status: "Pending",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=40&h=40&fit=crop&crop=center",
    name: "The Rustic Table",
    location: "Austin, TX",
    totalBookings: "654",
    revenue: "$25,680",
    rating: "4.3",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=40&h=40&fit=crop&crop=center",
    name: "Coastal Cuisine",
    location: "Seattle, WA",
    totalBookings: "1,023",
    revenue: "$47,890",
    rating: "4.6",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=40&h=40&fit=crop&crop=center",
    name: "Garden Terrace",
    location: "Portland, OR",
    totalBookings: "567",
    revenue: "$22,340",
    rating: "4.2",
    status: "Inactive",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=40&h=40&fit=crop&crop=center",
    name: "Metropolitan Dining",
    location: "Boston, MA",
    totalBookings: "1,445",
    revenue: "$68,920",
    rating: "4.8",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=40&h=40&fit=crop&crop=center",
    name: "Fire & Stone",
    location: "Phoenix, AZ",
    totalBookings: "789",
    revenue: "$34,560",
    rating: "4.4",
    status: "Active",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=40&h=40&fit=crop&crop=center",
    name: "Lakeside Pavilion",
    location: "Minneapolis, MN",
    totalBookings: "432",
    revenue: "$18,750",
    rating: "4.1",
    status: "Pending",
  },
];
